# Social, canonical and structured-data tags for every page, plus sitemap.xml
# and robots.txt.
#
# Before this the site had none of it: pasting a product link into Messenger or
# WhatsApp -- the way a distributor's links actually travel -- produced a bare
# URL with no title, image or description, and nothing told search engines that
# the Georgian and English pages are translations of one another.
#
# Re-runnable: the block is fenced by markers and replaced wholesale, so this
# can be run again after any page changes.
$repo = Split-Path $PSScriptRoot -Parent
$BASE = 'https://erekle13tabagari-web.github.io/biomi-website-demo'   # no CNAME yet; change here if a domain is added
$OGDIR = Join-Path $repo 'assets\img\og'
New-Item -ItemType Directory -Force -Path $OGDIR | Out-Null

$ORG = @{
  ka = @{ name='ბიომი ჰოლდინგი'; addr='აკაკი ბელიაშვილის 124'; city='თბილისი' }
  en = @{ name='Biomi Holding';  addr='Akaki Beliashvili 124'; city='Tbilisi' }
}
$SAMEAS = @(
  'https://www.facebook.com/p/Biomi-Holding-ბიომი-ჰოლდინგი-61579642613208/',
  # Percent-encoded, and www rather than the ge. locale host: the short
  # "biomi-holding" slug 404s, and sameAs is what Google reads to tie the
  # company's profiles together -- a dead URL in here is worse than no URL.
  'https://www.linkedin.com/company/biomi-holding-%E2%80%A2-%E1%83%91%E1%83%98%E1%83%9D%E1%83%9B%E1%83%98-%E1%83%B0%E1%83%9D%E1%83%9A%E1%83%93%E1%83%98%E1%83%9C%E1%83%92%E1%83%98',
  'https://www.instagram.com/biomi.holding/',
  # The handle, matching the button in the floating stack rather than adding a
  # second address for one channel. Its permanent id, should the handle ever be
  # renamed, is UCujeFl7hb813mSmb5JG4KtQ.
  'https://www.youtube.com/@BiomiHolding'
)

function Esc($s) { if ($null -eq $s) { return '' }; ($s -replace '&(?!(amp|lt|gt|quot|#\d+);)','&amp;' -replace '"','&quot;') }
function J($s)   { if ($null -eq $s) { return '' }; ($s -replace '\\','\\' -replace '"','\"' -replace '\s+',' ').Trim() }

$files = Get-ChildItem $repo -Filter '*.html' -Recurse -File |
         Where-Object { $_.Name -ne 'Launch Biomi Website.html' -and $_.FullName -notmatch '\\(backup|_files|\.git|\.claude|tools)' } |
         Sort-Object FullName

# ---------------------------------------------------------------- OG images
# Social scrapers do not render AVIF, so every card image is baked to JPEG at
# the 1.91:1 ratio Facebook and LinkedIn crop to.
$ogFor = @{}
$made = @{}
foreach ($f in $files) {
  $txt = [IO.File]::ReadAllText($f.FullName)
  $m = [regex]::Match($txt, '(?s)<div class="pgal__main">.*?<img src="([^"]+)"')
  if (-not $m.Success) { $ogFor[$f.FullName] = 'default'; continue }
  $rel = $m.Groups[1].Value -replace '^\.\./',''
  $src = Join-Path $repo ($rel -replace '/','\')
  if (-not (Test-Path -LiteralPath $src)) { $ogFor[$f.FullName] = 'default'; continue }
  $key = (Split-Path (Split-Path $src -Parent) -Leaf) + '-' + [IO.Path]::GetFileNameWithoutExtension($src)
  $ogFor[$f.FullName] = $key
  if (-not $made.ContainsKey($key)) {
    $made[$key] = $true
    & magick $src -resize 1000x520 -background white -alpha remove -alpha off `
             -gravity center -extent 1200x630 -quality 82 (Join-Path $OGDIR ($key + '.jpg'))
  }
}
$def = Join-Path $OGDIR 'default.jpg'
$defSrc = Join-Path $repo 'assets\img\about-us.webp'
if (Test-Path $defSrc) { & magick $defSrc -resize 1200x630^ -gravity center -extent 1200x630 -quality 82 $def }

# ------------------------------------------------------------------- pages
# Pages that still exist and still work on their own URL, but are not offered
# anywhere: nothing links to them, they carry robots noindex, and they are kept
# out of sitemap.xml. Take a name out of this list to publish it again.
$HIDDEN = 'service.html', 'service-en.html'

$urls = New-Object System.Collections.ArrayList
foreach ($f in $files) {
  $txt = [IO.File]::ReadAllText($f.FullName)
  $rel = $f.FullName.Substring($repo.Length + 1) -replace '\\','/'
  $en  = $f.Name -like '*-en.html'
  $lang = if ($en) { 'en' } else { 'ka' }
  $kaRel = if ($en) { $rel -replace '-en\.html$','.html' } else { $rel }
  $enRel = if ($en) { $rel } else { $rel -replace '\.html$','-en.html' }
  $hasPair = Test-Path (Join-Path $repo (($(if ($en) { $kaRel } else { $enRel })) -replace '/','\'))

  $title = ([regex]::Match($txt,'(?s)<title>(.*?)</title>')).Groups[1].Value.Trim()
  $desc  = ([regex]::Match($txt,'<meta name="description" content="([^"]*)"')).Groups[1].Value.Trim()
  $og    = $ogFor[$f.FullName]; if (-not (Test-Path (Join-Path $OGDIR ($og + '.jpg')))) { $og = 'default' }
  $canon = "$BASE/$rel"

  $b = New-Object System.Text.StringBuilder
  [void]$b.AppendLine('<!-- meta:start (generated by tools/build-meta.ps1 - do not edit by hand) -->')
  [void]$b.AppendLine('<link rel="canonical" href="' + $canon + '">')
  # Not $hidden: PowerShell variable names are case-insensitive, so assigning
  # to that would overwrite $HIDDEN with a boolean on the first page and every
  # test after it would be false.
  $isHidden = $HIDDEN -contains $f.Name
  if ($isHidden) { [void]$b.AppendLine('<meta name="robots" content="noindex,nofollow">') }
  if ($hasPair) {
    [void]$b.AppendLine('<link rel="alternate" hreflang="ka" href="' + "$BASE/$kaRel" + '">')
    [void]$b.AppendLine('<link rel="alternate" hreflang="en" href="' + "$BASE/$enRel" + '">')
    [void]$b.AppendLine('<link rel="alternate" hreflang="x-default" href="' + "$BASE/$kaRel" + '">')
  }
  [void]$b.AppendLine('<meta property="og:type" content="website">')
  [void]$b.AppendLine('<meta property="og:site_name" content="' + (Esc $ORG[$lang].name) + '">')
  [void]$b.AppendLine('<meta property="og:locale" content="' + $(if ($en) { 'en_US' } else { 'ka_GE' }) + '">')
  [void]$b.AppendLine('<meta property="og:title" content="' + (Esc $title) + '">')
  [void]$b.AppendLine('<meta property="og:description" content="' + (Esc $desc) + '">')
  [void]$b.AppendLine('<meta property="og:url" content="' + $canon + '">')
  [void]$b.AppendLine('<meta property="og:image" content="' + "$BASE/assets/img/og/$og.jpg" + '">')
  [void]$b.AppendLine('<meta property="og:image:width" content="1200">')
  [void]$b.AppendLine('<meta property="og:image:height" content="630">')
  [void]$b.AppendLine('<meta name="twitter:card" content="summary_large_image">')
  [void]$b.AppendLine('<meta name="twitter:title" content="' + (Esc $title) + '">')
  [void]$b.AppendLine('<meta name="twitter:description" content="' + (Esc $desc) + '">')
  [void]$b.AppendLine('<meta name="twitter:image" content="' + "$BASE/assets/img/og/$og.jpg" + '">')

  # ---- structured data
  $isProduct = $txt -match 'class="spec-table' -and $txt -match 'class="pgal__main"'
  if ($isProduct) {
    $brand = switch -Regex ($f.Name) {
      '^samsung'    { 'Samsung' }
      '^mitsubishi' { 'Mitsubishi Electric' }
      '^vortice'    { 'Vortice' }
      default       { $ORG[$lang].name }
    }
    $h1 = ([regex]::Match($txt,'(?s)<h1>(.*?)</h1>')).Groups[1].Value -replace '<[^>]+>',''
    [void]$b.AppendLine('<script type="application/ld+json">{"@context":"https://schema.org","@type":"Product",' +
      '"name":"' + (J $h1) + '","description":"' + (J $desc) + '",' +
      '"image":"' + "$BASE/assets/img/og/$og.jpg" + '",' +
      '"brand":{"@type":"Brand","name":"' + (J $brand) + '"},' +
      '"url":"' + $canon + '"}</script>')
  }
  if ($f.Name -like 'index*') {
    $o = $ORG[$lang]
    [void]$b.AppendLine('<script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization",' +
      '"name":"' + (J $o.name) + '","url":"' + $BASE + '/' + $rel + '",' +
      '"logo":"' + $BASE + '/assets/img/logo-geo.svg",' +
      '"telephone":"+995322151115","email":"info@biomi.ge",' +
      '"address":{"@type":"PostalAddress","streetAddress":"' + (J $o.addr) + '","addressLocality":"' + (J $o.city) + '","addressCountry":"GE"},' +
      '"sameAs":[' + (($SAMEAS | ForEach-Object { '"' + (J $_) + '"' }) -join ',') + ']}</script>')
  }
  [void]$b.AppendLine('<!-- meta:end -->')

  # replace any previous block, then insert before </head>
  $txt = [regex]::Replace($txt, '(?s)[ \t]*<!-- meta:start.*?<!-- meta:end -->\r?\n', '')
  $txt = $txt -replace '(?=</head>)', $b.ToString()
  # With the BOM: every HTML file in the repo carries one, and writing these
  # without it rewrote all 176 pages for nothing every time this ran.
  # sitemap.xml and robots.txt below stay BOM-less, which is correct for them.
  [IO.File]::WriteAllText($f.FullName, $txt, (New-Object Text.UTF8Encoding($true)))
  if (-not $isHidden) { [void]$urls.Add(@{ loc = $canon; ka = "$BASE/$kaRel"; en = "$BASE/$enRel"; pair = $hasPair }) }
}

# ----------------------------------------------------------------- sitemap
$today = (Get-Item (Join-Path $repo 'index.html')).LastWriteTime.ToString('yyyy-MM-dd')
$sm = New-Object System.Text.StringBuilder
[void]$sm.AppendLine('<?xml version="1.0" encoding="UTF-8"?>')
[void]$sm.AppendLine('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">')
foreach ($u in $urls) {
  [void]$sm.AppendLine('  <url>')
  [void]$sm.AppendLine('    <loc>' + $u.loc + '</loc>')
  if ($u.pair) {
    [void]$sm.AppendLine('    <xhtml:link rel="alternate" hreflang="ka" href="' + $u.ka + '"/>')
    [void]$sm.AppendLine('    <xhtml:link rel="alternate" hreflang="en" href="' + $u.en + '"/>')
  }
  [void]$sm.AppendLine('    <lastmod>' + $today + '</lastmod>')
  [void]$sm.AppendLine('  </url>')
}
[void]$sm.AppendLine('</urlset>')
[IO.File]::WriteAllText((Join-Path $repo 'sitemap.xml'), $sm.ToString(), (New-Object Text.UTF8Encoding($false)))

[IO.File]::WriteAllText((Join-Path $repo 'robots.txt'),
  "User-agent: *`nAllow: /`n`nSitemap: $BASE/sitemap.xml`n", (New-Object Text.UTF8Encoding($false)))

Write-Host ("pages tagged   : " + $files.Count)
Write-Host ("og images      : " + (Get-ChildItem $OGDIR -Filter '*.jpg').Count)
Write-Host ("sitemap urls   : " + $urls.Count)
Write-Host ("product schema : " + @($files | Where-Object { [IO.File]::ReadAllText($_.FullName) -match '"@type":"Product"' }).Count)
